package net.lshift.example;
/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ceri' at '16/10/17 11:06' with Gradle 2.10
 *
 * @author ceri, @date 16/10/17 11:06
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
