package net.lshift.example;
import com.google.common.collect.ImmutableList;
import org.junit.Test;
import static org.junit.Assert.*;
import static org.mockito.Mockito.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ceri' at '16/10/17 11:06' with Gradle 2.10
 *
 * @author ceri, @date 16/10/17 11:06
 */
public class LibraryTest {
    Shelves shelves = mock(Shelves.class);
    Library library = new Library(shelves);


    @Test
    public void shouldSayWhenBookIsPresent() {
        when(shelves.listBooks()).thenReturn(ImmutableList.of("Necronomicon", "Evil Dead"));
        assertTrue(library.hasBook("Necronomicon"));
    }

    @Test
    public void shouldSayWhenBookIsNotPresent() {
        when(shelves.listBooks()).thenReturn(ImmutableList.of("I love bees"));
        assertFalse(library.hasBook("Necronomicon"));
    }
}
